In [3]:
import numpy as np

In [6]:
a2 = np.array ([[1,2],[4,5],[6,7],[8,9]])
print(a2)

[[1 2]
 [4 5]
 [6 7]
 [8 9]]


In [7]:
a2.ndim

2

In [16]:
a2[:]

array([[1, 2],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
len(a2)

4

In [9]:
a2.shape

(4, 2)

In [18]:
a3 = np.array([[1,2,4,5],[6,7,4,3],[60,70,40,30],[16,17,14,13],[26,27,24,23]])
a3

array([[ 1,  2,  4,  5],
       [ 6,  7,  4,  3],
       [60, 70, 40, 30],
       [16, 17, 14, 13],
       [26, 27, 24, 23]])

In [19]:
a3[2]

array([60, 70, 40, 30])

In [20]:
a3[:]

array([[ 1,  2,  4,  5],
       [ 6,  7,  4,  3],
       [60, 70, 40, 30],
       [16, 17, 14, 13],
       [26, 27, 24, 23]])

In [21]:
a3[2:5]

array([[60, 70, 40, 30],
       [16, 17, 14, 13],
       [26, 27, 24, 23]])

In [22]:
a3.sum()

392

In [23]:
a3.mean()

19.6

In [24]:
a3[:]

array([[ 1,  2,  4,  5],
       [ 6,  7,  4,  3],
       [60, 70, 40, 30],
       [16, 17, 14, 13],
       [26, 27, 24, 23]])

In [25]:
a3[2].sum

<function ndarray.sum>

In [26]:
a3[1:5 ,2]

array([ 4, 40, 14, 24])

In [27]:
a3[:,2]

array([ 4,  4, 40, 14, 24])

In [28]:
a3.sum(axis=0)

array([109, 123,  86,  74])

In [30]:
a3.sum(axis=0)[2]

86

In [31]:
a3.sum(axis =1)

array([ 12,  20, 200,  60, 100])

In [32]:
a3.shape

(5, 4)

In [33]:
a3.reshape(4,5)

array([[ 1,  2,  4,  5,  6],
       [ 7,  4,  3, 60, 70],
       [40, 30, 16, 17, 14],
       [13, 26, 27, 24, 23]])

In [34]:
a3.shape

(5, 4)

In [36]:
a3.T

array([[ 1,  6, 60, 16, 26],
       [ 2,  7, 70, 17, 27],
       [ 4,  4, 40, 14, 24],
       [ 5,  3, 30, 13, 23]])

In [37]:
np.linspace(10 ,100 ,50)

array([ 10.        ,  11.83673469,  13.67346939,  15.51020408,
        17.34693878,  19.18367347,  21.02040816,  22.85714286,
        24.69387755,  26.53061224,  28.36734694,  30.20408163,
        32.04081633,  33.87755102,  35.71428571,  37.55102041,
        39.3877551 ,  41.2244898 ,  43.06122449,  44.89795918,
        46.73469388,  48.57142857,  50.40816327,  52.24489796,
        54.08163265,  55.91836735,  57.75510204,  59.59183673,
        61.42857143,  63.26530612,  65.10204082,  66.93877551,
        68.7755102 ,  70.6122449 ,  72.44897959,  74.28571429,
        76.12244898,  77.95918367,  79.79591837,  81.63265306,
        83.46938776,  85.30612245,  87.14285714,  88.97959184,
        90.81632653,  92.65306122,  94.48979592,  96.32653061,
        98.16326531, 100.        ])

In [38]:
np.linspace(10 ,100 ,50 , retstep=True)

(array([ 10.        ,  11.83673469,  13.67346939,  15.51020408,
         17.34693878,  19.18367347,  21.02040816,  22.85714286,
         24.69387755,  26.53061224,  28.36734694,  30.20408163,
         32.04081633,  33.87755102,  35.71428571,  37.55102041,
         39.3877551 ,  41.2244898 ,  43.06122449,  44.89795918,
         46.73469388,  48.57142857,  50.40816327,  52.24489796,
         54.08163265,  55.91836735,  57.75510204,  59.59183673,
         61.42857143,  63.26530612,  65.10204082,  66.93877551,
         68.7755102 ,  70.6122449 ,  72.44897959,  74.28571429,
         76.12244898,  77.95918367,  79.79591837,  81.63265306,
         83.46938776,  85.30612245,  87.14285714,  88.97959184,
         90.81632653,  92.65306122,  94.48979592,  96.32653061,
         98.16326531, 100.        ]), 1.836734693877551)

In [39]:
np.arange(10,100,5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [40]:
np.random.randint(100)

86

In [41]:
np.random.randint(50,100)

53

In [42]:
np.random.randint(50,100,7)

array([99, 62, 77, 83, 53, 85, 75])

In [49]:
np.random.seed(53)

In [51]:
np.random.seed(53)
np.random.randint(100000,999999)

289213

In [53]:
np.random.random(5)

array([0.56116554, 0.4548754 , 0.35217491, 0.58585138, 0.53574974])